---
- name: Install SigNoz K8S‑Infra metrics chart
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    namespace: signoz-system
    release_name: k8s-infra
    chart_repo_name: signoz
    chart_repo_url: https://charts.signoz.io
    chart_name: signoz/k8s-infra
    chart_version: "0.13.0"
    otel_collector_endpoint: "{{ lookup('env','DOCKER_HOST_IP') }}:4317"
    k8s_cluster_name: codespace-demo
    deployment_environment: development

  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present

    - name: Add SigNoz Helm repo (and force update)
      kubernetes.core.helm_repository:
        name: "{{ chart_repo_name }}"
        repo_url: "{{ chart_repo_url }}"
        state: present
        force_update: yes

    - name: Install or upgrade k8s‑infra chart
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: "{{ chart_name }}"
        release_namespace: "{{ namespace }}"
        chart_version: "{{ chart_version }}"
        create_namespace: false
        values:
          global:
            clusterName: "{{ k8s_cluster_name }}"
            deploymentEnvironment: "{{ deployment_environment }}"
          otelCollectorEndpoint: "{{ otel_collector_endpoint }}"
          otelInsecure: true
          presets:
            otlpExporter:
              enabled: true
            loggingExporter:
              enabled: false
            hostMetrics:
              enabled: true
            kubeletMetrics:
              enabled: true
            clusterMetrics:
              enabled: true
          otelAgent:
            ports:
              otlp:       { hostPort: null }
              otlp-http:  { hostPort: null }
              metrics:    { hostPort: null }
              health-check: { hostPort: null }
        state: present
