---
galaxy_info:
  author: Your Name
  description: Ansible role to deploy rolldice sample application with OpenTelemetry instrumentation
  company: 
  license: MIT
  min_ansible_version: 2.10
  platforms:
  - name: GenericLinux
    versions:
    - all
  galaxy_tags:
  - kubernetes
  - application
  - opentelemetry
  - testing
  - telemetry

dependencies:
  - name: kubernetes.core
    version: ">=2.3.0"
