apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
  namespace: k8sinfra
  labels:
    app: rolldice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
        - name: rolldice
          image: nginx:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rolldice
  namespace: k8sinfra   # <-- Add this line
spec:
  selector:
    app: rolldice
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort