---
# Example configuration for different environments

# Development Environment (default)
development:
  signoz_otel_endpoint: "192.168.1.100:4317"  # Your TrueNAS SigNoz instance
  cluster_name: "dev-k8s-cluster"
  deployment_environment: "development"
  k8sinfra_values:
    presets:
      logsCollection:
        enabled: true
      hostMetrics:
        enabled: true
      kubeletMetrics:
        enabled: true
      clusterMetrics:
        enabled: true

# Production Environment
production:
  signoz_otel_endpoint: "prod-signoz.example.com:4317"
  cluster_name: "prod-k8s-cluster"
  deployment_environment: "production"
  k8sinfra_values:
    presets:
      logsCollection:
        enabled: true
      hostMetrics:
        enabled: true
      kubeletMetrics:
        enabled: true
      clusterMetrics:
        enabled: true

# Testing Environment (minimal monitoring)
testing:
  signoz_otel_endpoint: "test-signoz.example.com:4317"
  cluster_name: "test-k8s-cluster"
  deployment_environment: "testing"
  k8sinfra_values:
    presets:
      logsCollection:
        enabled: false  # Disable logs in testing
      hostMetrics:
        enabled: true
      kubeletMetrics:
        enabled: true
      clusterMetrics:
        enabled: false  # Disable cluster metrics in testing
