---
- name: Create monitoring namespace
  kubernetes.core.k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: true

- name: Create override values file for k8s-infra
  ansible.builtin.tempfile:
    state: file
    suffix: "-k8sinfra-values.yaml"
  register: k8sinfra_values_file

- name: Write k8s-infra values to temporary file
  ansible.builtin.copy:
    content: "{{ k8sinfra_values | to_nice_yaml }}"
    dest: "{{ k8sinfra_values_file.path }}"

- name: Deploy k8s-infra helm chart
  kubernetes.core.helm:
    name: "{{ k8sinfra_release_name }}"
    chart_ref: signoz/k8s-infra
    chart_version: "{{ k8sinfra_chart_version | default(omit) }}"
    release_namespace: "{{ k8s_namespace }}"
    create_namespace: false
    values_files:
      - "{{ k8sinfra_values_file.path }}"
    state: present
    wait: true
    wait_timeout: 600

- name: Display k8s-infra deployment status
  ansible.builtin.debug:
    msg: |
      K8s-infra chart deployed successfully!
      Release name: {{ k8sinfra_release_name }}
      Namespace: {{ k8s_namespace }}
      OTEL Collector Endpoint: {{ signoz_otel_endpoint }}
      
      To verify deployment, run:
      kubectl get pods -n {{ k8s_namespace }}
      kubectl get services -n {{ k8s_namespace }}

- name: Wait for k8s-infra pods to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ k8s_namespace }}"
    label_selectors:
      - "app.kubernetes.io/instance={{ k8sinfra_release_name }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  register: k8sinfra_pods

- name: Clean up temporary values file
  ansible.builtin.file:
    path: "{{ k8sinfra_values_file.path }}"
    state: absent
