---
- name: Deploy Kubernetes Infrastructure Monitoring with SigNoz
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - group_vars/all.yaml
  
  tasks:
    - name: Add SigNoz Helm repository
      kubernetes.core.helm_repository:
        name: signoz
        repo_url: https://charts.signoz.io
        state: present

    - name: Update helm repositories
      kubernetes.core.helm:
        name: dummy
        chart_ref: signoz/k8s-infra
        release_namespace: "{{ k8s_namespace }}"
        update_repo_cache: yes
      ignore_errors: yes

  roles:
    - k8sinfra
    - rolldice
